defaults: &defaults
  working_directory: ~/app
  docker:
    - image: cypress/browsers:chrome67

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      # find compatible cache from previous build,
      # it should have same dependencies installed from package.json checksum
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      # save new cache folder if needed
      - save_cache:
          key: cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      # all other test jobs will run AFTER this build job finishes
      # to avoid reinstalling dependencies, we persist the source folder "app"
      # and the Cypress binary to workspace, which is the fastest way
      # for Circle jobs to pass files
      - persist_to_workspace:
          root: ~/
          paths:
            - app
            - .cache/Cypress

  tests:
    <<: *defaults
    steps:
      # restore application and Cypress binary before running the test command
      - attach_workspace:
          at: ~/
      - run:
          name: Start server
          command: npm start
          background: true
      # run all tests
      - run:
          name: Run Cypress tests
          command: $(npm bin)/cypress run

workflows:
  version: 2
  # "build" installs NPM dependencies so other jobs don't have to
  build_and_test:
    jobs:
      - build
      # after installing dependencies in the "build" job
      # run all tests in several groups
      #     group "1x-electron"
      - tests:
          requires:
            - build